language: java

sudo: false

# No much sense in keeping jdbi artifacts cached
before_cache:
  rm -rf $HOME/.m2/repository/org/jdbi

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - build/ci-pre-install.sh

install:
  - build/ci-install.sh

jdk: oraclejdk8

